# Generated by Django 5.0.6 on 2024-05-23 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_make_returned', 'Set book as returned'),)},
        ),
    ]
